# docker-compose.yaml
version: '3.3'
services:
  jenkins:
    build:
      context: /home/liel/CD_Pipeline_Exercise
      dockerfile: Dockerfile-controller
    # image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/liel/code/jenkins/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  agent:
          #depends_on:
          #  - jenkins
    # image: jenkins/ssh-agent:jdk11
    build:
      context: /home/liel/CD_Pipeline_Exercise
      dockerfile: Dockerfile-old-agent
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCU3EoP20NwUULJO6YoV3HeWlA6NWlbUCyJ4G+dOfj7HRCnj/3jCXzKIftLQsxq+ZzFMvcUwo87u3DYoEQ6EE2orIUcER+FygTfiGLG2bqndsGojohGlqFY95LDStWNkgBUg6FRsYHnsnGPk+/gz/4hE0v8MCe3mvRl1ZI8VeSdfOHFxKDWgBkQG+/CCzVKek4XWbegt//rcVrY9JcpAZwkefdEsTaW1roE13OOU/SC/QoQRWc3mofe4ny0Hz4GUoQA91e10RG7OAIDKpxM0AvghUT8TuPJUcDPWSMIxMUuo/+R9vGgV+4sZNAM0bgmI3cwg1H7TEYSuLzxId5YTx71EEKDW3WoEy3dQOGVj8IuE9PLIRHjdkSGEcpWRWeZuUb4uzgeOEdRJbSsDfEhCPaFYjBItPhUe0/RF7KWhvsni9zv+FKB1OAF9eGmd8EuBplbi+I2ZhXCmLCsR44Wnb//VtxbNfkQZV9nva+ImAgzxfHk2Gtsik3NzDlynBbcvHk= root@liel-virtual-machine
